-- Run in the Supabase SQL editor. All timestamps below are JavaScript epoch milliseconds.
create table if not exists public.activities (
  id text primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  type text not null check (type in ('running', 'cycling')),
  title text,
  notes text,
  start_time bigint not null,
  end_time bigint,
  moving_time_ms bigint not null default 0,
  paused_duration_ms bigint not null default 0,
  total_distance double precision not null default 0,
  avg_speed double precision not null default 0,
  max_speed double precision not null default 0,
  calories_burned double precision not null default 0,
  updated_at bigint not null,
  deleted_at bigint,
  route_plan_id text
);

create table if not exists public.location_points (
  id bigint generated by default as identity primary key,
  point_key text not null unique,
  activity_id text references public.activities (id) on delete cascade not null,
  user_id uuid references auth.users (id) on delete cascade not null,
  sequence bigint not null default 0,
  segment integer not null default 0,
  latitude double precision not null,
  longitude double precision not null,
  timestamp bigint not null,
  accuracy double precision
);
create index if not exists idx_location_points_activity on public.location_points (activity_id);

create table if not exists public.splits (
  id text primary key,
  activity_id text references public.activities (id) on delete cascade not null,
  user_id uuid references auth.users (id) on delete cascade not null,
  split_index integer not null,
  distance_meters double precision not null,
  duration_ms bigint not null,
  avg_speed double precision not null,
  updated_at bigint not null
);

create table if not exists public.goals (
  id text primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  activity_type text not null check (activity_type in ('running', 'cycling')),
  weekly_distance_meters double precision not null,
  updated_at bigint not null,
  unique (user_id, activity_type)
);

create table if not exists public.profiles (
  id uuid references auth.users (id) on delete cascade primary key,
  weight_kg double precision not null default 65,
  height_cm double precision not null default 170,
  age integer not null default 30,
  sex text not null default 'unspecified' check (sex in ('female', 'male', 'unspecified')),
  display_name text,
  avatar_data text,
  updated_at timestamptz not null default now()
);

-- Safe upgrades for projects that used the original RunTrackerApp schema.
alter table public.activities add column if not exists title text;
alter table public.activities add column if not exists notes text;
alter table public.activities add column if not exists moving_time_ms bigint not null default 0;
alter table public.activities add column if not exists paused_duration_ms bigint not null default 0;
alter table public.activities add column if not exists updated_at bigint;
alter table public.activities add column if not exists deleted_at bigint;
alter table public.activities add column if not exists route_plan_id text;
update public.activities set updated_at = coalesce(updated_at, start_time) where updated_at is null;
alter table public.activities alter column updated_at set not null;

alter table public.profiles add column if not exists height_cm double precision not null default 170;
alter table public.profiles add column if not exists age integer not null default 30;
alter table public.profiles add column if not exists sex text not null default 'unspecified';
alter table public.profiles add column if not exists avatar_data text;

alter table public.location_points add column if not exists point_key text;
alter table public.location_points add column if not exists sequence bigint not null default 0;
alter table public.location_points add column if not exists segment integer not null default 0;
alter table public.location_points add column if not exists accuracy double precision;
update public.location_points
set point_key = activity_id || ':' || timestamp || ':' || id
where point_key is null;
create unique index if not exists idx_location_points_point_key on public.location_points (point_key);
alter table public.location_points alter column point_key set not null;

alter table public.activities enable row level security;
alter table public.location_points enable row level security;
alter table public.splits enable row level security;
alter table public.goals enable row level security;
alter table public.profiles enable row level security;

drop policy if exists "activities owner access" on public.activities;
drop policy if exists "points owner access" on public.location_points;
drop policy if exists "splits owner access" on public.splits;
drop policy if exists "goals owner access" on public.goals;
drop policy if exists "profiles owner access" on public.profiles;
drop policy if exists "activities: owner rw" on public.activities;
drop policy if exists "location_points: owner rw" on public.location_points;
drop policy if exists "profiles: owner rw" on public.profiles;

create policy "activities owner access" on public.activities for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "points owner access" on public.location_points for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "splits owner access" on public.splits for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "goals owner access" on public.goals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "profiles owner access" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);

-- Explicit API privileges make the schema work even when the project was
-- created without Supabase's usual default grants. RLS above still isolates users.
grant select, insert, update, delete on public.activities to authenticated;
grant select, insert, update, delete on public.location_points to authenticated;
grant select, insert, update, delete on public.splits to authenticated;
grant select, insert, update, delete on public.goals to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

notify pgrst, 'reload schema';
